# Generated by Django 5.0.7 on 2024-08-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('titulo', models.CharField(max_length=255)),
                ('estudios', models.CharField(max_length=255)),
                ('produtores', models.TextField()),
                ('vencedor', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'filmes',
                'managed': True,
            },
        ),
    ]
